using System.Text;
using Sling.Persistence.Workspaces;

namespace Sling.Persistence.Tests;

/// <summary>
/// Which files a <c>&lt; ./file</c> import is allowed to read.
/// </summary>
/// <remarks>
/// The containment rules, tested against a real file system because that is where they
/// are enforced. A <c>.http</c> file is shared, pasted from a colleague, or generated by
/// importing somebody's Postman collection - so a document naming a private key and
/// posting it elsewhere is ordinary input, not an exotic attack.
/// </remarks>
public sealed class WorkspaceFileSourceTests
{
    [Fact]
    public void A_relative_path_inside_the_workspace_is_read()
    {
        using var folder = new TemporaryFolder();
        folder.Write("requests/payload.json", """{"a":1}""");

        var source = new WorkspaceFileSource(Path.Combine(folder.Path, "requests"), folder.Path);

        Assert.True(source.TryRead("./payload.json", out var bytes, out _));
        Assert.Equal("""{"a":1}""", Encoding.UTF8.GetString(bytes));
    }

    [Fact]
    public void A_path_reaching_up_into_the_workspace_is_read()
    {
        // A shared fixtures folder beside the requests is the ordinary arrangement, so
        // '..' is not itself the thing being refused - leaving the root is.
        using var folder = new TemporaryFolder();
        folder.Write("fixtures/payload.json", "{}");

        var source = new WorkspaceFileSource(Path.Combine(folder.Path, "requests"), folder.Path);

        Assert.True(source.TryRead("../fixtures/payload.json", out _, out _));
    }

    [Fact]
    public void An_absolute_path_is_refused()
    {
        using var folder = new TemporaryFolder();
        var outside = Path.Combine(Path.GetTempPath(), "sling-tests", "outside.txt");
        Directory.CreateDirectory(Path.GetDirectoryName(outside)!);
        File.WriteAllText(outside, "secret");

        try
        {
            var source = new WorkspaceFileSource(folder.Path, folder.Path);

            Assert.False(source.TryRead(outside, out _, out var reason));
            Assert.Contains("relative", reason, StringComparison.Ordinal);
        }
        finally
        {
            File.Delete(outside);
        }
    }

    [Theory]
    [InlineData("../../../../../../Windows/win.ini")]
    [InlineData("../outside.txt")]
    public void A_path_that_walks_out_of_the_workspace_is_refused(string path)
    {
        using var folder = new TemporaryFolder();

        var source = new WorkspaceFileSource(folder.Path, folder.Path);

        Assert.False(source.TryRead(path, out _, out var reason));
        Assert.Contains("outside", reason, StringComparison.Ordinal);
    }

    [Fact]
    public void A_sibling_folder_whose_name_starts_with_the_root_is_outside_it()
    {
        // The classic way this check is got wrong: a string prefix test says
        // 'C:\work\api-secrets' is inside 'C:\work\api'.
        using var parent = new TemporaryFolder();
        var root = Path.Combine(parent.Path, "api");
        Directory.CreateDirectory(root);
        parent.Write("api-secrets/key.pem", "PRIVATE KEY");

        var source = new WorkspaceFileSource(root, root);

        Assert.False(source.TryRead("../api-secrets/key.pem", out _, out var reason));
        Assert.Contains("outside", reason, StringComparison.Ordinal);
    }

    [Fact]
    public void A_missing_file_says_so_rather_than_throwing()
    {
        using var folder = new TemporaryFolder();

        var source = new WorkspaceFileSource(folder.Path, folder.Path);

        Assert.False(source.TryRead("./nope.json", out _, out var reason));
        Assert.Contains("no such file", reason, StringComparison.Ordinal);
    }

    [Fact]
    public void With_no_workspace_the_documents_own_folder_is_the_boundary()
    {
        using var folder = new TemporaryFolder();
        folder.Write("outside.txt", "secret");
        Directory.CreateDirectory(Path.Combine(folder.Path, "requests"));

        var source = new WorkspaceFileSource(Path.Combine(folder.Path, "requests"), workspaceRoot: null);

        Assert.False(source.TryRead("../outside.txt", out _, out _));
    }

    [Fact]
    public void A_workspace_that_does_not_contain_the_document_does_not_widen_the_boundary()
    {
        // Happens whenever a file is opened from outside the folder that is open. Taking
        // that folder as the root would let the document read a tree it is not even in.
        using var elsewhere = new TemporaryFolder();
        using var document = new TemporaryFolder();

        elsewhere.Write("secrets.txt", "secret");
        document.Write("payload.json", "{}");

        var source = new WorkspaceFileSource(document.Path, elsewhere.Path);

        Assert.True(source.TryRead("./payload.json", out _, out _));
        Assert.False(source.TryRead(Path.Combine(elsewhere.Path, "secrets.txt"), out _, out _));
    }

    [Fact]
    public void A_link_whose_target_leaves_the_workspace_is_refused()
    {
        using var parent = new TemporaryFolder();
        var root = Path.Combine(parent.Path, "ws");
        Directory.CreateDirectory(root);
        parent.Write("outside/key.pem", "PRIVATE KEY");

        if (!TryLink(Path.Combine(root, "key.pem"), Path.Combine(parent.Path, "outside", "key.pem"), directory: false))
        {
            return;
        }

        var source = new WorkspaceFileSource(root, root);

        Assert.False(source.TryRead("./key.pem", out _, out var reason));
        Assert.Contains("link", reason, StringComparison.Ordinal);
    }

    [Fact]
    public void A_link_on_an_intermediate_folder_is_refused_too()
    {
        // The hole the leaf check left open. FileInfo.ResolveLinkTarget inspects only the
        // entry it is called on and Path.GetFullPath is purely lexical, so a directory
        // symlink or junction anywhere above the file was invisible to both - and a repo
        // with a committed 'fixtures -> ../../' link read straight out of the workspace.
        using var parent = new TemporaryFolder();
        var root = Path.Combine(parent.Path, "ws");
        Directory.CreateDirectory(root);
        parent.Write("outside/key.pem", "PRIVATE KEY");

        if (!TryLink(Path.Combine(root, "fixtures"), Path.Combine(parent.Path, "outside"), directory: true))
        {
            return;
        }

        var source = new WorkspaceFileSource(root, root);

        Assert.False(source.TryRead("./fixtures/key.pem", out _, out var reason));
        Assert.Contains("link", reason, StringComparison.Ordinal);
    }

    [Fact]
    public void A_link_that_stays_inside_the_workspace_is_read()
    {
        // The mirror case. Refusing every link would break the ordinary arrangement of a
        // shared fixtures folder reached through one.
        using var folder = new TemporaryFolder();
        folder.Write("shared/payload.json", "{}");
        Directory.CreateDirectory(Path.Combine(folder.Path, "requests"));

        if (!TryLink(
            Path.Combine(folder.Path, "requests", "fixtures"),
            Path.Combine(folder.Path, "shared"),
            directory: true))
        {
            return;
        }

        var source = new WorkspaceFileSource(Path.Combine(folder.Path, "requests"), folder.Path);

        Assert.True(source.TryRead("./fixtures/payload.json", out _, out _));
    }

    [Theory]
    [InlineData("http-client.private.env.json")]
    [InlineData("http-client.env.json")]
    [InlineData("nested/http-client.private.env.json")]
    public void An_environment_file_is_refused_even_though_it_is_inside_the_workspace(string path)
    {
        // The secrets file lives at the root by definition, so containment alone lets a
        // document read it - a shorter path to the credential than the private key this
        // class was written to refuse. A shared .http file POSTing it elsewhere is two
        // lines long.
        using var folder = new TemporaryFolder();
        folder.Write(path, """{ "prod": { "token": "s3cret" } }""");

        var source = new WorkspaceFileSource(folder.Path, folder.Path);

        Assert.False(source.TryRead("./" + path, out _, out var reason));
        Assert.Contains("environment file", reason, StringComparison.Ordinal);
    }

    [Fact]
    public void An_unusably_long_path_is_reported_rather_than_thrown()
    {
        // The interface promises failures come back as text. GetFullPath throws
        // PathTooLongException as well as ArgumentException, and only the latter was
        // caught - so this escaped as the window's generic "could not complete the request".
        using var folder = new TemporaryFolder();

        var source = new WorkspaceFileSource(folder.Path, folder.Path);

        Assert.False(source.TryRead("./" + new string('a', 40_000), out _, out var reason));
        Assert.NotNull(reason);
    }

    /// <summary>
    /// Creates a link, or reports that this machine will not let us.
    /// </summary>
    /// <remarks>
    /// Windows requires either Developer Mode or elevation to create a symbolic link. A
    /// test that cannot create one has nothing to say, and failing the suite on an
    /// unprivileged machine would teach people to ignore it - so it stands down rather
    /// than asserting something it did not set up.
    /// </remarks>
    private static bool TryLink(string path, string target, bool directory)
    {
        try
        {
            if (directory)
            {
                Directory.CreateSymbolicLink(path, target);
            }
            else
            {
                File.CreateSymbolicLink(path, target);
            }

            return true;
        }
        catch (IOException)
        {
            return false;
        }
        catch (UnauthorizedAccessException)
        {
            return false;
        }
    }
}
